services:
  - type: pg
    name: culture-card-bot-db
    plan: free
    databaseName: culture_card_bot
    user: culture_card_bot_user

  - type: worker
    name: culture-card-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DEBUG_LOG_ENABLED
        value: false
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: culture-card-bot-db
          property: connectionString



