services:
  - type: pg
    name: celebrate-the-world-db
    plan: free
    databaseName: celebrate_the_world_bot
    user: celebrate_the_world_user

  - type: worker
    name: celebrate-the-world-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DEBUG_LOG_ENABLED
        value: false
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: celebrate-the-world-db
          property: connectionString



